vim.cmd("set tabstop=2")
vim.cmd("set shiftwidth=2")
vim.cmd("set softtabstop=0")
vim.cmd("set expandtab")
vim.cmd("set list")
vim.cmd("set lcs+=space:·")
vim.cmd("set number relativenumber")
vim.cmd("runtime macros/matchit.vim")
vim.cmd("filetype plugin on")
